using UnityEngine;
using System.Collections;
using System.Xml;
using System.IO;

public class item_populate : MonoBehaviour {


	public int uid; // unique id generated by this class 

	void Start () {
		uid = 0;

		XmlReader reader = XmlReader.Create ("assets/items.xml");
		while (reader.Read()) {
			if( (reader.IsStartElement("item"))  ){
				uid++;
				GameObject item = Instantiate(Resources.Load("item")) as GameObject;
				item.name = (uid).ToString();

				item.GetComponent<item_script>().bid = reader.GetAttribute("bid");
				item.GetComponent<item_script>().uid = uid.ToString();

				item.GetComponent<item_script>().itemname = reader.GetAttribute("name");
				item.GetComponent<item_script>().examine = reader.GetAttribute("examine");
				item.GetComponent<item_script>().type = reader.GetAttribute("type");
			}
		}
	}

	public void CreateGameObject(string bid){

		XmlReader reader = XmlReader.Create ("assets/items.xml");

		while (reader.Read() ) {
			if( (reader.IsStartElement("item"))   && (reader.GetAttribute("bid")==bid)){
				GameObject item = Instantiate(Resources.Load("item")) as GameObject;
				item.name = (uid++).ToString();
				
				item.GetComponent<item_script>().bid = reader.GetAttribute("bid");
				item.GetComponent<item_script>().uid = uid.ToString();
				
				item.GetComponent<item_script>().itemname = reader.GetAttribute("name");
				item.GetComponent<item_script>().examine = reader.GetAttribute("examine");
				item.GetComponent<item_script>().type = reader.GetAttribute("type");



			}
		}

	}
	
	void Update () {
	
	}
}
